# Generated by Django 3.2.16 on 2022-12-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('created_date', models.TimeField(auto_now_add=True)),
                ('updated_date', models.TimeField(auto_now=True)),
            ],
        ),
    ]
